### ISSUE TITLE
OGC_EDR examples

### ISSUE THREAD

**Issue by miguelcorreia19** [ILIAD-ocean-twin/data_access_api#1]
When the command `pygeoapi openapi generate $PYGEOAPI_CONFIG --output-file $PYGEOAPI_OPENAPI` is executed it gets the following error:

`pygeoapi.provider.base.ProviderConnectionError: 'EntryPoints' object has no attribute 'get'`

This is with the [example-config-edr.yml](https://github.com/ILIAD-ocean-twin/data_access_api/blob/main/examples/OGC_EDR/configs/example-config-edr.yml) file.

**Comment by pzaborowski** [comment]
installation procedure updated for EDR, please check
